### ISSUE TITLE
only options

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/load-helpers#1]
If only one object is given it will be interpreted as `cache` not as `options`, so the code won't work as user may expect. Yea, they can read the readme, but.. you know, i think it's always better to some smart checks for these things, like "if arguments.length === 1, then interpret given object as options", will be enough, imo.

**Comment by jonschlinkert** [comment]
lol we just got done doing this and @doowb and I both agreed that it should be strict. maybe the simpler solution is to have just options and pass `options.cache` for the cache?

**Comment by tunnckoCore** [comment]
lol, yea i just have notifications from rss channels, one of them is your activity stream, so yea.. i can react immediately :D 

Yea seems better and logical move.

**Comment by jonschlinkert** [comment]
no I was laughing about it b/c we were just saying the same exact thing, and b/c I took the easy way out I think I said something like "I know someone will give me a hard time for this" then 5 min later you made the issue lol.

**Comment by jonschlinkert** [comment]
closing since this was refactored
